In [1]:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

In [2]:
array_list

array([1, 2, 3, 4, 5])

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

## Ans:- variable_list:- The list is an important component used to collect multiple items in a single variable. It has the ability to collect items that usually consist of elements of multiple data types. These may include character logical values, numeric values, and more.
## List cannot manage arithmetic operations.
## It consists of elements that belong to the different data types.
## When it comes to flexibility, the list is perfect as it allows easy modification of data.
## It consumes a larger memory

## array_list:-An array is also a vital component that collects several items of same type. Arrays are also known as data structure. Python has several in-built data structures, such as arrays.
## Array can manage arithmetic operations.
## It consists of elements that belong to the same data type.
## When it comes to flexibility, the array is not suitable as it does not allow easy modification of data.
## It does not consume larger memory

In [5]:
variable_list=[1,2,3,4,'dikshant',7,5,'rajput']

In [6]:
print(variable_list)
print(array_list)

[1, 2, 3, 4, 'dikshant', 7, 5, 'rajput']
[1 2 3 4 5]


In [7]:
a=[1,2,3,4]
b=[4,5,6,7]

In [8]:
a+b ## does not manage airthmatic operation

[1, 2, 3, 4, 4, 5, 6, 7]

In [15]:
array_list2=np.array([1,2,3,4,5])
print(array_list2)
print(array_list)
print(array_list+array_list2)

[1 2 3 4 5]
[1 2 3 4 5]
[ 2  4  6  8 10]


In [16]:
array_list[0]=12

In [17]:
array_list

array([12,  2,  3,  4,  5])

## Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

## Ans:-

In [37]:
list_

[1, 2, 3, 4, 5]

In [38]:
for i in list_:
    print(i,type(i))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
5 <class 'int'>


In [23]:
array_list

array([12,  2,  3,  4,  5])

In [27]:
for i in array_list:
    print(i,type(array_list))

12 <class 'numpy.ndarray'>
2 <class 'numpy.ndarray'>
3 <class 'numpy.ndarray'>
4 <class 'numpy.ndarray'>
5 <class 'numpy.ndarray'>


## Q3. Considering the following changes in the variable, array_list:
## array_list = np.array(object = list_, dtype = int)
## Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables list_ and array_list.


In [28]:
array_list = np.array(object = list_ ,dtype=int)

In [32]:
array_list

array([1, 2, 3, 4, 5])

In [34]:
for i in array_list:
    print(i,type(i))

1 <class 'numpy.int64'>
2 <class 'numpy.int64'>
3 <class 'numpy.int64'>
4 <class 'numpy.int64'>
5 <class 'numpy.int64'>


In [35]:
list_

[1, 2, 3, 4, 5]

In [36]:
for i in list_:
    print(i,type(i))

1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4 <class 'int'>
5 <class 'int'>


##  no difference in data type between the elements of array_list and list_

## consider the following:- 

In [40]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [41]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

## Q4. Write a code to find the following characteristics of variable, num_array:
## (i) shape
## (ii) size

In [42]:
num_array.shape

(2, 3)

In [43]:
num_array.size

6

## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [45]:
array=np.zeros([3,3])

In [46]:
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
array.size

9

In [48]:
array.shape

(3, 3)

## Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [52]:
array2=np.eye(5,5)

In [53]:
array2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
array2.shape

(5, 5)

In [55]:
array2.size

25